Ryze.System.Web/Views/Shared/ViewComponents/BreadcrumbViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ryze.System.Web.Models;

namespace Ryze.System.Web.Views.Shared.ViewComponents
{
    public class BreadcrumbViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<BreadcrumbItem> items)
        {
            if (items == null)
            {
                items = new List<BreadcrumbItem>();
            }

            return View(items);
        }
    }
}

Ryze.System.Web/Views/Shared/ViewComponents/MessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ryze.System.Web.Models;

namespace Ryze.System.Web.Views.Shared.ViewComponents
{
    public class MessageViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string? message = null, string? success = null, string? errors = null)
        {
            var messages = new MessageViewModel
            {
                Message = message,
                Success = success,
                Errors = errors
            };

            return View(messages);
        }
    }
}

Ryze.System.Web/Views/Shared/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Ryze.System.Application.Services.Users;
using Ryze.System.Domain.Entity.Identity;

namespace Ryze.System.Web.Views.Shared.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;

        public NavbarViewComponent(UserManager<ApplicationUser> userManager, IUserService userService)
        {
            _userManager = userManager;
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);           
            var userData = await _userService.GetUserById(user.Id);

            return View(userData);
        }
    }

}

Ryze.System.Web/Views/Shared/ViewComponents/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ryze.System.Web.Models;

namespace Ryze.System.Web.Views.Shared.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int totalItems, int currentPage, int pageSize, string action, string controller, string? area = "")
        {
            var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize);

            var model = new PaginationViewModel
            {
                CurrentPage = currentPage,
                TotalPages = totalPages,
                PageSize = pageSize,
                Action = action,
                Controller = controller,
                Area = area
            };

            return View(model);
        }
    }
}

Ryze.System.Web/Views/Shared/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Ryze.System.Application.Services.Tickets;
using Ryze.System.Domain.Entity.Identity;

namespace Ryze.System.Web.Views.Shared.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly ITicketService _ticketService;
        private readonly UserManager<ApplicationUser> _userManager;

        public SidebarViewComponent(ITicketService ticketService, UserManager<ApplicationUser> userManager)
        {
            _ticketService = ticketService;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            //if (user == null) return View(new Dictionary<StatusEnum, int>());

            //var ticketCounts = await _ticketService.GetTicketCountsByUserId(user.Id);
            return View(user);
        }
    }
}

Ryze.System.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Manager Tickets</title>

    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/kaiadmin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/plugins.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/demo.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/System.Tickets.Web.styles.css" asp-append-version="true" />

    <!-- Fonts and icons -->
    <script src="~/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { families: ["Public Sans:300,400,500,600,700"] },
            custom: {
                families: [
                    "Font Awesome 5 Solid",
                    "Font Awesome 5 Regular",
                    "Font Awesome 5 Brands",
                    "simple-line-icons",
                ],
                urls: ["@Url.Content("~/css/fonts.min.css")"],
            },
            active: function () {
                sessionStorage.fonts = true;
            },
        });
    </script>

</head>
<body>
    <div class="wrapper">
        @await Component.InvokeAsync("Sidebar")

        <div class="main-panel">
            <div class="main-header">
                <div class="main-header-logo">
                    <!-- Logo Header -->
                    <div class="logo-header" data-background-color="dark">
                        <a href="index.html" class="logo">
                            <img src="assets/img/kaiadmin/logo_light.svg"
                                 alt="navbar brand"
                                 class="navbar-brand"
                                 height="20" />
                        </a>
                        <div class="nav-toggle">
                            <button class="btn btn-toggle toggle-sidebar">
                                <i class="gg-menu-right"></i>
                            </button>
                            <button class="btn btn-toggle sidenav-toggler">
                                <i class="gg-menu-left"></i>
                            </button>
                        </div>
                        <button class="topbar-toggler more">
                            <i class="gg-more-vertical-alt"></i>
                        </button>
                    </div>
                    <!-- End Logo Header -->
                </div>
                @await Component.InvokeAsync("Navbar")
            </div>
            <div class="container">
                <div class="page-inner">
                    <div class="page-header">
                        <h4 class="page-title">Dashboard</h4>
                        @await Component.InvokeAsync("Breadcrumb", ViewData["Breadcrumbs"] as List<BreadcrumbItem>)
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-sm-8 col-lg-8"></div>
                        <div class="col-md-4 col-sm-4 col-lg-4">
                            @await Component.InvokeAsync("Message", new { message = TempData["Message"] as string, success = TempData["Success"] as string, errors = TempData["Errors"] as string })
                        </div>
                    </div>
                    @RenderBody()
                </div>
            </div>
            @await Html.PartialAsync("~/Views/Shared/Components/Footer/_Footer.cshtml")
        </div>
    </div>

    <script src="~/js/core/jquery-3.7.1.min.js"></script>
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>
    <script src="~/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/js/plugin/sweetalert/sweetalert.min.js"></script>
    <script src="~/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
    <script src="~/js/kaiadmin.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $('#message-container .alert').alert('close');
            }, 2000);
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>